# Generated by Django 3.0.6 on 2020-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200813_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('sValue', models.TextField(blank=True, null=True)),
                ('iValue', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
