# Generated by Django 3.0.6 on 2020-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
