# Generated by Django 3.1 on 2020-08-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200817_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVisitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('visit_count', models.IntegerField()),
            ],
        ),
    ]
