# Generated by Django 3.1 on 2020-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_articlevisitmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='coverimg',
            field=models.TextField(default='banner-1.png'),
        ),
    ]
