# Generated by Django 3.1 on 2020-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_coverimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_white',
            field=models.IntegerField(default=0),
        ),
    ]
