# Generated by Django 3.1 on 2020-09-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200830_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
