# Generated by Django 3.1 on 2020-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200912_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.IntegerField(default=0),
        ),
    ]
