# Generated by Django 3.1 on 2020-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pa40commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pa40commentmodel',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
